### ISSUE TITLE
Add instructions for using the library

### ISSUE THREAD

**Issue by pawan-jenu** [fabianishere/ktor-oauth2#1]

**Comment by fabianishere** [comment]
Hi!

I do not have instructions on using the API other than the documentation in the codebase. However, for an example where I have used this library, please look at [booklab](https://github.com/fabianishere/booklab), in particular the `booklab-backend` module where I used it to host an OAuth2 authorization server.

**Comment by pawan-jenu** [comment]
documentation in codebase ? could you provide the link!
Thanks!

**Comment by fabianishere** [comment]
I am referring to the source code: https://github.com/fabianishere/ktor-oauth2/tree/master/src/main/kotlin/io/ktor/auth/oauth2

**Comment by pawan-jenu** [comment]
i have another issue, actually i was planning to build a oauth server using ktor, will your framework be helpful for me? and could you suggest any guide for the same!

**Comment by fabianishere** [comment]
I actually created this library since there were no OAuth2 servers available for Ktor. However, at the moment, I would suggest using [kotlin-oauth2-server](https://github.com/myndocs/kotlin-oauth2-server) until I add instructions for using the library.

**Comment by pawan-jenu** [comment]
could i make a server like yours in ktor ? for managing my api's

**Comment by fabianishere** [comment]
Yes, just follow the instructions given by the other library I linked.

**Comment by pawan-jenu** [comment]
alright, i will have a look at it, but i got one doubt, when i clone your repo, i am not able to run it/ could you help me with that one part!

thanks

**Comment by fabianishere** [comment]
That's correct, since the repository does not contain a (working) example at the moment.

**Comment by pawan-jenu** [comment]
so your mean i cant use your library currently ?
when would you make it working ?

**Comment by fabianishere** [comment]
You could, but you need to figure out yourself how to integrate it in your Ktor application. The best example I can give you right now is [booklab](https://github.com/fabianishere/booklab).

**Comment by pawan-jenu** [comment]
alright i will have a look at it? thank you
